--7.1 COMPUTER AND PLC STATUS REPORT
GO
USE [BHSDB_OKC];
GO

--1. COMPUTER STATUS
--OLD
--SELECT	MELM.EQUIP_ID, 
--		MESV.STATUS_NAME AS 'ONOFF_STATUS',
--		CASE MESV.STATUS_NAME
--			WHEN 'Offline' THEN 'Standby'
--			WHEN 'Online' THEN 'Running'
--		END	AS 'WORKING_STATUS'
--FROM	MIS_EQUIP_LIVE_MONITOR MELM, MIS_EQUIP_STATUS_VALUEMAP MESV
--WHERE	MELM.STATUS_CLASS=MESV.STATUS_CLASS
--	AND MELM.CURRENT_STATUS=MESV.STATUS_VALUE
--	AND (MELM.EQUIP_ID NOT LIKE 'PLC%' AND MELM.EQUIP_ID NOT LIKE 'UPS%')
--	AND MELM.STATUS_CLASS='ON_OFFLINE';


SELECT	STA.LOCATION AS EQUIP_ID, 
		LTRIM(RTRIM(STAL.DESCRIPTION))  AS 'ONOFF_STATUS',
		CASE STAL.DESCRIPTION
			WHEN 'OFFLINE' THEN 'Standby' 
			WHEN 'ONLINE' THEN 'Running'
		END	AS 'WORKING_STATUS'
FROM	MDS_STATUS STA, MDS_STATUS_LK STAL
WHERE	STA.TYPE='NETWORK' 
	AND STA.TYPE=STAL.TYPE 
	AND STA.TYPE_STATUS=STAL.TYPE_STATUS 
	AND LTRIM(RTRIM(STA.STATUS))=LTRIM(RTRIM(STAL.FIX))
	AND STAL.DESC_TYPE='FIX'
	AND (STA.LOCATION LIKE 'MES%' 
		OR STA.LOCATION LIKE '%MDS%' 
		OR STA.LOCATION LIKE 'SAC%'
		OR STA.LOCATION LIKE 'MON%'
		OR STA.LOCATION LIKE 'OWS%')
ORDER BY STA.LOCATION

--2. SORT CONTROLLER
SELECT APP_CODE, LIVE_STATUS_TYPE
FROM APP_LIVE_MONITORING
WHERE APP_CODE LIKE 'BHSDB%' OR APP_CODE LIKE 'MDS%' OR APP_CODE LIKE 'SAC%'

--3. PLC BANK
--SELECT	MELM.EQUIP_ID, 
--		MESV.STATUS_NAME AS 'ONOFF_STATUS',
--		( SELECT MESV2.STATUS_NAME
--		  FROM MIS_EQUIP_LIVE_MONITOR MELM2, MIS_EQUIP_STATUS_VALUEMAP MESV2
--		  WHERE MELM2.STATUS_CLASS=MESV2.STATUS_CLASS
--				AND MELM2.CURRENT_STATUS=MESV2.STATUS_VALUE
--				AND MELM2.EQUIP_ID=MELM.EQUIP_ID
--				AND MELM.STATUS_CLASS='PRI_SEC'
--		 ) AS 'WORKING_STATUS'
--FROM	MIS_EQUIP_LIVE_MONITOR MELM, MIS_EQUIP_STATUS_VALUEMAP MESV
--WHERE	MELM.STATUS_CLASS=MESV.STATUS_CLASS
--	AND MELM.CURRENT_STATUS=MESV.STATUS_VALUE
--	AND MELM.EQUIP_ID LIKE 'PLC%'
--	AND MELM.STATUS_CLASS='ON_OFFLINE';

SELECT	STA.LOCATION AS EQUIP_ID, 
		LTRIM(RTRIM(STAL.DESCRIPTION))  AS 'ONOFF_STATUS',
		CASE STAL.DESCRIPTION
			WHEN 'OFFLINE' THEN 'Standby' 
			WHEN 'ONILNE' THEN 'Running'
		END	AS 'WORKING_STATUS'
FROM	MDS_STATUS STA, MDS_STATUS_LK STAL
WHERE	STA.TYPE='NETWORK' 
	AND STA.TYPE=STAL.TYPE 
	AND STA.TYPE_STATUS=STAL.TYPE_STATUS 
	AND LTRIM(RTRIM(STA.STATUS))=LTRIM(RTRIM(STAL.FIX))
	AND STAL.DESC_TYPE='FIX'
	AND STA.LOCATION LIKE 'PLC%'
ORDER BY STA.LOCATION


--4. UPS STATS

