GO
USE [BHSDB];
GO


CREATE PROCEDURE dbo.stp_RPT06_EquipOperation_Diverter
		@DTFrom [datetime],
		@DTTo [datetime],
		@SubSystem varchar(MAX)
AS
BEGIN

	SELECT	MBCR.SUBSYSTEM, 
			MBCR.LOCATION AS DIVERTER_ID, 
			CASE
				WHEN MBCR.DESCRIPTION LIKE '%EXTENDED%' THEN 'EXTENDED' --extended
				WHEN MBCR.DESCRIPTION LIKE '%HOME%' THEN 'HOME' --retract
				ELSE 'WRONG TYPE'
			END AS MOVE_TYPE,
			SUM(DIFFERENT) AS MOVE_CNT

	INTO	#EOD_DIVERTER_TEMP

	FROM	MDS_BAG_COUNT MBC, 
			MDS_BAG_COUNTERS MBCR WITH(NOLOCK)

	WHERE	MBC.COUNTER_ID=MBCR.COUNTER_ID
			AND (MBCR.COUNTER_ID LIKE '%EXT%' OR MBCR.COUNTER_ID LIKE '%RTC%') --May be other name
			AND (MBCR.DESCRIPTION LIKE '%EXTENDED%' OR MBCR.DESCRIPTION LIKE '%HOME%') --May be other name
			AND MBCR.SUBSYSTEM IN (SELECT * FROM RPT_GETPARAMETERS(@SubSystem))
			AND MBC.TIME_STAMP BETWEEN @DTFrom AND @DTTo 

	GROUP BY	MBCR.SUBSYSTEM,
				MBCR.LOCATION,
				CASE
					WHEN MBCR.DESCRIPTION LIKE '%EXTENDED%' THEN 'EXTENDED' --extended
					WHEN MBCR.DESCRIPTION LIKE '%HOME%' THEN 'HOME' --retract
					ELSE 'WRONG TYPE'
				END;


	SELECT	EXT_DIVR.SUBSYSTEM,
			EXT_DIVR.DIVERTER_ID,
			EXT_DIVR.MOVE_CNT AS EXTENDED_CNT,
			HME_DIVR.MOVE_CNT AS HOME_CNT
	FROM	#EOD_DIVERTER_TEMP EXT_DIVR,
			#EOD_DIVERTER_TEMP HME_DIVR
	WHERE	EXT_DIVR.SUBSYSTEM=HME_DIVR.SUBSYSTEM
		AND EXT_DIVR.DIVERTER_ID=HME_DIVR.DIVERTER_ID
		AND EXT_DIVR.MOVE_TYPE='HOME'
		AND HME_DIVR.MOVE_TYPE='EXTENDED';

	
END

--DECLARE @DTFrom datetime='2013-11-01';
--DECLARE @DTTo datetime='2013-12-25';
--DECLARE @Subsystem varchar(max)='ED1,ED2,ED3,ED4,SS1,SS2';
--EXEC stp_RPT06_EquipOperation_Diverter @DTFrom,@DTTo,@Subsystem;