GO
USE [BHSDB_OKC];
GO


ALTER PROCEDURE dbo.stp_RPT_OKC_EquipOperation_HSPD
		@DTFrom [datetime],
		@DTTo [datetime],
		@SubSystem varchar(MAX)
AS
BEGIN

	SELECT	MBCR.SUBSYSTEM, 
			MBCR.LOCATION AS DIVERTER_ID, 
			CASE LTRIM(RTRIM(MBCR.TYPE_STATUS))
				WHEN 'EXTEND' THEN 'EXTENDED' --extended
				WHEN 'RETRACT' THEN 'HOME' --retract
				ELSE 'WRONG TYPE'
			END AS MOVE_TYPE,
			SUM(DIFFERENT) AS MOVE_CNT
	INTO	#EOD_DIVERTER_TEMP
	FROM	MDS_COUNT MBC, 
			MDS_COUNTERS MBCR WITH(NOLOCK)
	WHERE	MBC.COUNTER_ID=MBCR.COUNTER_ID
			AND MBCR.TYPE='HSD'
			AND (LTRIM(RTRIM(MBCR.TYPE_STATUS)) = 'EXTEND' OR LTRIM(RTRIM(MBCR.TYPE_STATUS)) = 'RETRACT')
			AND MBCR.SUBSYSTEM IN (SELECT * FROM RPT_GETPARAMETERS(@SubSystem))
			AND MBC.TIME_STAMP BETWEEN @DTFrom AND @DTTo 
	GROUP BY	MBCR.SUBSYSTEM,
				MBCR.LOCATION,
				CASE LTRIM(RTRIM(MBCR.TYPE_STATUS))
					WHEN 'EXTEND' THEN 'EXTENDED' --extended
					WHEN 'RETRACT' THEN 'HOME' --retract
					ELSE 'WRONG TYPE'
				END;

	--select * from #EOD_6DIVERTER_TEMP

	SELECT	EXT_DIVR.SUBSYSTEM,
			EXT_DIVR.DIVERTER_ID,
			EXT_DIVR.MOVE_CNT AS EXTENDED_CNT,
			HME_DIVR.MOVE_CNT AS HOME_CNT
	FROM	#EOD_DIVERTER_TEMP EXT_DIVR,
			#EOD_DIVERTER_TEMP HME_DIVR
	WHERE	EXT_DIVR.SUBSYSTEM=HME_DIVR.SUBSYSTEM
		AND EXT_DIVR.DIVERTER_ID=HME_DIVR.DIVERTER_ID
		AND EXT_DIVR.MOVE_TYPE='HOME'
		AND HME_DIVR.MOVE_TYPE='EXTENDED';

	
END

--DECLARE @DTFrom datetime='2014-04-05';
--DECLARE @DTTo datetime='2014-04-07';
--DECLARE @Subsystem varchar(max)='ED1,ED2,ED3,ED4,SS1,SS2';
--EXEC stp_RPT_CLT_EquipOperation_Diverter @DTFrom,@DTTo,@Subsystem;