GO
USE [BHSDB];
GO


ALTER PROCEDURE dbo.stp_RPT0502_EquipCorrection
		  @DTFrom datetime, 
		  @DTTo datetime,
		  @Subsystem varchar(max),
		  @EquipmentID varchar(max),
		  @FaultType varchar(max)
AS
BEGIN
	SELECT	ALM_ALMAREA1 AS ALM_SUBSYSTEM, 
			ALM_ALMEXTFLD2 AS ALM_EQUIPID, 
			ALM_STARTTIME AS ALM_TIMESET,
			ALM_ENDTIME AS ALM_TIMECLEAR, 
			ALM_MSGDESC AS ALM_DESCRIPTION,
			CASE
				WHEN ALM_ENDTIME IS NOT NULL THEN DATEDIFF(SECOND,ALM_STARTTIME,ALM_ENDTIME)
				ELSE 0
			END  AS ALM_DURATION
	FROM	MDS_ALARMS WITH(NOLOCK)
	WHERE	ALM_UNCERTAIN = 0
			AND ALM_STARTTIME BETWEEN @DTFrom AND @DTTo 
			AND ALM_ALMAREA1 IN (SELECT * FROM dbo.RPT_GETPARAMETERS(@Subsystem)) 
			AND ALM_ALMEXTFLD2 IN (SELECT * FROM dbo.RPT_GETPARAMETERS(@EquipmentID)) 
			AND ALM_ALMAREA2 IN (SELECT * FROM dbo.RPT_GETPARAMETERS(@FaultType))
	ORDER BY ALM_STARTTIME
END

--DECLARE @DTFrom datetime='2014/1/11 18:56:26' 
--DECLARE @DTTo datetime='2014/1/12 19:26:32'
--DECLARE @Subsystem varchar(max)='RI1'
--DECLARE @EquipmentID varchar(max)='RI1-04SD'
--DECLARE @FaultType varchar(max)='AA_SDAL'
--EXEC stp_RPT0502_EquipCorrection @DTFrom,@DTTo,@Subsystem,@EquipmentID,@FaultType;