GO
USE [BHSDB_OKC];
GO

CREATE PROCEDURE dbo.stp_RPT_OKC_SysCommBehavior
		  @DTFrom datetime, 
		  @DTTo datetime
AS
BEGIN
	DECLARE @FaultType varchar(max)='AA_NDAL';

	SELECT	ALM_ALMEXTFLD2 AS ALARM_EQUIPMENTID, --AS ALM_EQUIPID, 
			ALM_STARTTIME,
			ALM_ENDTIME,
			ALM_MSGDESC,
			CASE
				WHEN ALM_ENDTIME IS NOT NULL THEN DATEDIFF(SECOND,ALM_STARTTIME,ALM_ENDTIME)
				ELSE 0
			END  AS ALM_DURATION,
			LOC.INTERNAL_LOC AS HIDDEN_LOC
	FROM	MDS_ALARMS
	LEFT JOIN LOCATIONS LOC WITH(NOLOCK)
			ON ALM_ALMAREA1=LOC.SUBSYSTEM AND ALM_ALMEXTFLD2=LOC.LOCATION
	WHERE	ALM_UNCERTAIN = 0
			AND ALM_STARTTIME BETWEEN @DTFrom AND @DTTo
			AND ALM_ALMAREA2 IN (SELECT * FROM dbo.RPT_GETPARAMETERS(@FaultType))
	ORDER BY LOC.SUBSYSTEM,LOC.INTERNAL_LOC,ALM_ALMAREA1,ALM_ALMEXTFLD2,ALM_STARTTIME
END