--14 DAY END REPORT
GO
USE [BHSDB];
GO

--1 THROUGHPUT INPUT

ALTER PROCEDURE dbo.stp_RPT14_DAYEND_INPUT
		  @DTFrom DATETIME,
		  @DTTo DATETIME
AS
BEGIN
	--SELECT	LOC.LOCATION AS 'LOCATION', 
	--		COUNT(GID.GID) AS 'COUNT' 
	--FROM GID_USED GID, LOCATIONS LOC WITH(NOLOCK)
	--WHERE	GID.BAG_TYPE='01'--normal bag
	--		AND GID.TIME_STAMP BETWEEN @DTFrom AND @DTTo 
	--		AND GID.LOCATION=LOC.LOCATION_ID
	--		AND EXISTS(SELECT GID_LOCATION FROM MIS_SS_LINE_DEVICE SLD WHERE LOC.LOCATION=SLD.GID_LOCATION)
	--GROUP BY LOC.LOCATION

	SELECT MBCR.SUBSYSTEM AS 'LOCATION',SUM(MBC.DIFFERENT) AS 'COUNT'
	FROM MDS_BAG_COUNT MBC, MDS_BAG_COUNTERS MBCR WITH(NOLOCK)
	WHERE MBC.COUNTER_ID=MBCR.COUNTER_ID
	AND MBC.TIME_STAMP BETWEEN @DTFrom AND @DTTo 
	AND (MBCR.SUBSYSTEM LIKE '%TC%' OR MBCR.SUBSYSTEM LIKE '%IC%' OR MBCR.SUBSYSTEM LIKE '%CS%' OR MBCR.SUBSYSTEM LIKE 'OS%')
	GROUP BY MBCR.SUBSYSTEM;
END

--declare @DTFrom datetime='2013-12-18';
--declare @DTTo datetime='2013-12-22';
--EXEC stp_RPT14_DAYEND_INPUT @DTFrom,@DTTo;

--2 ATR STATS

GO
USE [BHSDB];
GO
ALTER PROCEDURE dbo.stp_RPT14_DAYEND_ATRSTATS
		  @DTFrom DATETIME,
		  @DTTo DATETIME,
		  @ATRUNITS varchar(MAX)
AS
BEGIN
	CREATE TABLE #DAYEND_ATRSTATUS_TEMP
	(
		ATRUNIT VARCHAR(20),
		COUNT_BAGSSEEN INT,
		COUNT_BAGSREAD INT,
		COUNT_NOREAD INT,
		COUNT_VALIDTAGS INT,
		COUNT_CONFLICT_TAGS INT,
		COUNT_NOBSM INT,
		COUNT_LATEBAGS INT,
		READ_RATE FLOAT
	);

	INSERT INTO #DAYEND_ATRSTATUS_TEMP
	EXEC stp_RPT12_ATR_OVERALL_STATISTIC_GWYTEST @DTFrom,@DTTo,@ATRUNITS

	SELECT ATRUNIT, COUNT_BAGSSEEN, COUNT_BAGSREAD, COUNT_LATEBAGS, READ_RATE
	FROM #DAYEND_ATRSTATUS_TEMP;

	DROP TABLE #DAYEND_ATRSTATUS_TEMP;
END

declare @DTFrom datetime='2013-12-18';
declare @DTTo datetime='2013-12-27';
DECLARE @ATRUNITS varchar(MAX)='SS1-2,SS2-2,SS2-2,SS3-2,ML1-2,ML2-2,ML3-2,ML4-2';
EXEC stp_RPT14_DAYEND_ATRSTATS @DTFrom,@DTTo,@ATRUNITS;

--3 BDD STATS
--PROBLEM1: BAGS READ=BAGCNT_NORMAL?
GO
USE [BHSDB];
GO
ALTER PROCEDURE dbo.stp_RPT14_DAYEND_BDDSTATS
		  @DTFrom DATETIME,
		  @DTTo DATETIME
AS
BEGIN
	CREATE TABLE #DAYEND_BDDSTATUS_TEMP
	(
		BDD_ARRAY VARCHAR(20),
		BAGCNT_SEEN INT,
		BAGCNT_DIM INT,
		BAGCNT_OOG INT,
		BAGCNT_NORMAL INT,
		BAGCNT_NOTDIM INT
	)
	INSERT INTO #DAYEND_BDDSTATUS_TEMP
	EXEC stp_RPT24_BDDSTATISTICS_OOG_GWYTEST @DTFrom,@DTTo

	SELECT BDD_ARRAY,BAGCNT_NORMAL AS BAGS_READ, BAGCNT_DIM AS BAGS_DIM
	FROM #DAYEND_BDDSTATUS_TEMP;

	DROP TABLE #DAYEND_BDDSTATUS_TEMP;
END

--declare @DTFrom datetime='2013-12-18';
--declare @DTTo datetime='2013-12-27';
--EXEC stp_RPT14_DAYEND_BDDSTATS @DTFrom,@DTTo

--4 MES STATS
GO
USE [BHSDB];
GO
ALTER PROCEDURE dbo.stp_RPT14_DAYEND_MESSTATS
		  @DTFrom DATETIME,
		  @DTTo DATETIME
AS
BEGIN
	SELECT LOC.LOCATION AS MES_STATION, COUNT(DISTINCT MER.GID) AS BAGS
	FROM ITEM_ENCODING_REQUEST MER, LOCATIONS LOC WITH(NOLOCK)
	WHERE MER.TIME_STAMP BETWEEN @DTFrom AND @DTTo
		AND MER.LOCATION=LOC.LOCATION_ID
	GROUP BY LOC.SUBSYSTEM, LOC.LOCATION;
END

--declare @DTFrom datetime='2013-12-18';
--declare @DTTo datetime='2013-12-27';
--EXEC stp_RPT14_DAYEND_MESSTATS @DTFrom,@DTTo;

--5 EDS STATS

GO
USE [BHSDB];
GO
ALTER PROCEDURE dbo.stp_RPT14_DAYEND_EDSSTATS
		  @DTFrom DATETIME,
		  @DTTo DATETIME
AS
BEGIN
	CREATE TABLE #EDS_STATUS_TEMP
	(
		SUBSYSTEM_TYPE VARCHAR(30),
		SUBSYSTEM VARCHAR(20),
		BAGS INT,
		BAGS_CLEARED INT,
		BAGS_ALARMED INT,
		CLEARED_RATE FLOAT
	)

	INSERT INTO #EDS_STATUS_TEMP
	EXEC stp_RPT10_LOADBALANCING_EDS @DTFrom,@DTTo;

	SELECT SUBSYSTEM AS EDS_MACHINE, BAGS, BAGS_CLEARED, BAGS_ALARMED, CLEARED_RATE
	FROM #EDS_STATUS_TEMP
	WHERE SUBSYSTEM_TYPE='EDS MACHINES';

	DROP TABLE #EDS_STATUS_TEMP;
END

--declare @DTFrom datetime='2013-12-15';
--declare @DTTo datetime='2013-12-27';
--EXEC stp_RPT14_DAYEND_EDSSTATS @DTFrom,@DTTo;

--6 OUTPUTS

GO
USE [BHSDB];
GO
ALTER PROCEDURE dbo.stp_RPT14_DAYEND_OUTPUT
		  @DTFrom DATETIME,
		  @DTTo DATETIME
AS
BEGIN
	SELECT LOC.LOCATION AS OUTPUT_LOCATION, COUNT(IPR.GID) AS BAGS
	FROM ITEM_PROCEEDED IPR, LOCATIONS LOC
	WHERE IPR.PROCEED_LOCATION=LOC.LOCATION_ID
		AND LOC.LOCATION LIKE 'MU%'
		AND IPR.TIME_STAMP BETWEEN @DTFrom AND @DTTo
	GROUP BY LOC.LOCATION;
END

--declare @DTFrom datetime='2013-12-15';
--declare @DTTo datetime='2013-12-27';
--EXEC stp_RPT14_DAYEND_OUTPUT @DTFrom,@DTTo;

--7 TRACKING
DECLARE @SUBSYSTEM VARCHAR(MAX);
SELECT @SUBSYSTEM=COALESCE(@SUBSYSTEM+',' ,'')+SUBSYSTEM FROM SUBSYSTEMS
SELECT @SUBSYSTEM;
declare @DTFrom datetime='2013-12-15';
declare @DTTo datetime='2013-12-27';

EXEC stp_RPT23_TRACKEDPHOTOCELL @DTFrom,@DTTo,@SUBSYSTEM;

--SELECT * FROM MDS_BAG_COUNT MBC 
--WHERE MBC.TIME_STAMP BETWEEN @DTFrom AND @DTTo


