GO
USE [BHSDB_OKC];
GO


ALTER PROCEDURE dbo.stp_RPT_OKC_PermanentFlight
		--@DTFrom DATETIME,
		--@DTTo DATETIME,
		@AIRLINES VARCHAR(MAX),
		@FLIGHTS VARCHAR(MAX)
AS
BEGIN

	CREATE TABLE #TMP_PERMANENT_FLIGHT
	(
		AIRLINE VARCHAR(3),
		FLIGHT_NUMBER VARCHAR(5),
		WEEKDAYS VARCHAR(MAX),
		STO VARCHAR(5),
		RESOURCES VARCHAR(MAX)
	)

	--DECLARE @STO_FROM VARCHAR(4)=SUBSTRING(CONVERT(VARCHAR,@DTFrom,120),12,2)+SUBSTRING(CONVERT(VARCHAR,@DTFrom,120),15,2);
	--DECLARE @STO_TO VARCHAR(4)=SUBSTRING(CONVERT(VARCHAR,@DTTo,120),12,2)+SUBSTRING(CONVERT(VARCHAR,@DTTo,120),15,2);
	
	INSERT INTO #TMP_PERMANENT_FLIGHT
	SELECT	TFPA.AIRLINE, TFPA.FLIGHT_NUMBER, '' AS WEEKDAYS, DBO.RPT_GETFORMATTEDSTO(TFPA.STO) AS STO, '' AS RESOURCES
	FROM	TEMPLATE_FLIGHT_PLAN_ALLOC TFPA
	WHERE	TFPA.AIRLINE IN (SELECT * FROM DBO.RPT_GETPARAMETERS(@AIRLINES))
		AND TFPA.FLIGHT_NUMBER IN (SELECT * FROM DBO.RPT_GETPARAMETERS(@FLIGHTS))
		--AND TFPA.STO BETWEEN @STO_FROM AND @STO_TO

	DECLARE @SC_ALLOCINFO_TABLE AS ALLOCINFO_TABLETYPE; --For the parameter of stp_RPT_AllocInfoCombine
	DECLARE @SC_COMBINEINFO_TABLE AS ALLOCCOMINFO_TABLETYPE;--For the result of stp_RPT_AllocInfoCombine

	--4. UPDATE RESOURCES
	INSERT	INTO @SC_ALLOCINFO_TABLE
	SELECT	DISTINCT TFPA.AIRLINE,TFPA.FLIGHT_NUMBER,
			CONVERT(DATETIME,DBO.RPT_GETFORMATTEDSTO(TFPA.STO),120) AS STD,
			TFPA.RESOURCE
	FROM	TEMPLATE_FLIGHT_PLAN_ALLOC TFPA WITH(NOLOCK)

	INSERT INTO @SC_COMBINEINFO_TABLE
	EXEC DBO.stp_RPT_AllocInfoCombine @SC_ALLOCINFO_TABLE

	UPDATE TPF
	SET TPF.RESOURCES=COMB.COMBINEINFO
	FROM #TMP_PERMANENT_FLIGHT TPF, @SC_COMBINEINFO_TABLE COMB
	WHERE TPF.AIRLINE=COMB.AIRLINE AND TPF.FLIGHT_NUMBER=COMB.FLIGHT_NUMBER AND COMB.SDO=CONVERT(DATETIME,TPF.STO,120);

	--5. UPDATE WEEKDAYS
	DELETE @SC_ALLOCINFO_TABLE;
	DELETE @SC_COMBINEINFO_TABLE;

	INSERT	INTO @SC_ALLOCINFO_TABLE
	SELECT	DISTINCT TFPA.AIRLINE,TFPA.FLIGHT_NUMBER,
			CONVERT(DATETIME,DBO.RPT_GETFORMATTEDSTO(TFPA.STO),120) AS STD,
			TFPA.WEEKDAY
	FROM	TEMPLATE_FLIGHT_PLAN_ALLOC TFPA WITH(NOLOCK)

	INSERT INTO @SC_COMBINEINFO_TABLE
	EXEC DBO.stp_RPT_AllocInfoCombine @SC_ALLOCINFO_TABLE

	UPDATE TPF
	SET TPF.WEEKDAYS=COMB.COMBINEINFO
	FROM #TMP_PERMANENT_FLIGHT TPF, @SC_COMBINEINFO_TABLE COMB
	WHERE TPF.AIRLINE=COMB.AIRLINE AND TPF.FLIGHT_NUMBER=COMB.FLIGHT_NUMBER AND COMB.SDO=CONVERT(DATETIME,TPF.STO,120);

	SELECT * FROM #TMP_PERMANENT_FLIGHT;
	
END

--DECLARE @DTFrom datetime='2014-04-28 00:00:00';
--DECLARE @DTTo datetime='2014-04-28 23:00:00';
--DECLARE @AIRLINES VARCHAR(MAX)='AA,DL,UA';
--DECLARE @FLIGHTS VARCHAR(MAX)='3585,3587,3588,2560,2562';
--EXEC stp_RPT_OKC_PermanentFlight @DTFrom,@DTTo,@AIRLINES,@FLIGHTS;