GO
USE [BHSDB_OKC];
GO


ALTER PROCEDURE dbo.stp_RPT_OKC_SortAreaAssignment
		  @DTFrom datetime , 
		  @DTTo datetime
AS
BEGIN
	PRINT 'SortAreaAssignment STORED PROCEDURE BEGIN';

	--SELECT frc.CURRENT_RESOURCE as Physical_MakeUp, frc.NEW_RESOURCE as AssignedTo
	--FROM FLIGHT_RESOURCE_CHANGE frc
	--WHERE TIME_STAMP BETWEEN @DTFrom AND @DTTo

	SELECT	AR.RESOURCE as Physical_MakeUp,AR.RESOURCE as AssignedTo
	FROM	ALLOC_RESOURCES AR
END