--7.1 COMPUTER AND PLC STATUS REPORT
GO
USE [BHSDB];
GO

--1. COMPUTER STATUS
SELECT	MELM.EQUIP_ID, 
		MESV.STATUS_NAME AS 'ONOFF_STATUS',
		CASE MESV.STATUS_NAME
			WHEN 'Offline' THEN 'Standby'
			WHEN 'Online' THEN 'Running'
		END	AS 'WORKING_STATUS'
FROM	MIS_EQUIP_LIVE_MONITOR MELM, MIS_EQUIP_STATUS_VALUEMAP MESV
WHERE	MELM.STATUS_CLASS=MESV.STATUS_CLASS
	AND MELM.CURRENT_STATUS=MESV.STATUS_VALUE
	AND (MELM.EQUIP_ID NOT LIKE 'PLC%' AND MELM.EQUIP_ID NOT LIKE 'UPS%')
	AND MELM.STATUS_CLASS='ON_OFFLINE';

--2. SORT CONTROLLER
SELECT APP_CODE, LIVE_STATUS_TYPE
FROM APP_LIVE_MONITORING
WHERE APP_CODE LIKE 'BHSDB%' OR APP_CODE LIKE 'MDS%' OR APP_CODE LIKE 'SAC%'

--3. PLC BANK
SELECT	MELM.EQUIP_ID, 
		MESV.STATUS_NAME AS 'ONOFF_STATUS',
		( SELECT MESV2.STATUS_NAME
		  FROM MIS_EQUIP_LIVE_MONITOR MELM2, MIS_EQUIP_STATUS_VALUEMAP MESV2
		  WHERE MELM2.STATUS_CLASS=MESV2.STATUS_CLASS
				AND MELM2.CURRENT_STATUS=MESV2.STATUS_VALUE
				AND MELM2.EQUIP_ID=MELM.EQUIP_ID
				AND MELM.STATUS_CLASS='PRI_SEC'
		 ) AS 'WORKING_STATUS'
FROM	MIS_EQUIP_LIVE_MONITOR MELM, MIS_EQUIP_STATUS_VALUEMAP MESV
WHERE	MELM.STATUS_CLASS=MESV.STATUS_CLASS
	AND MELM.CURRENT_STATUS=MESV.STATUS_VALUE
	AND MELM.EQUIP_ID LIKE 'PLC%'
	AND MELM.STATUS_CLASS='ON_OFFLINE';


--4. UPS STATS
