GO
USE [BHSDB_OKC];
GO

create PROCEDURE dbo.stp_RPT_OKC_EDSMalfunction
		  @DTFrom datetime, 
		  @DTTo datetime
AS
BEGIN
	SELECT	ALM_ALMAREA1 AS ALM_SUBSYSTEM, 
			MALM.ALM_ALMEXTFLD2 AS EDS_ID, --ALM_ALMEXTFLD2,ELD.EDS_LOCATION
			ALM_STARTTIME, 
			ALM_ENDTIME,
			ALM_MSGDESC AS ALM_DESCRIPTION
	FROM	DBO.GET_RPT_EDS_LINE_DEVICE() AS ELD,
			MDS_ALARMS AS MALM WITH(NOLOCK)
	WHERE	MALM.ALM_ALMAREA1=ELD.SUBSYSTEM
			AND MALM.ALM_ALMEXTFLD2=('XR-'+ ELD.SUBSYSTEM)
			AND ALM_UNCERTAIN = 0
			AND ALM_STARTTIME BETWEEN @DTFrom AND @DTTo 
			AND MALM.ALM_MSGTYPE='ALARM'
			AND MALM.ALM_ALMAREA2<>'AA_RDRV'
	ORDER BY ALM_STARTTIME


END

--DECLARE @DTFrom datetime='2014-1-7';
--DECLARE @DTTo datetime='2014-1-10';
--EXEC stp_RPT21_EDSMalfunction @DTFrom,@DTTo