GO
USE [BHSDB];
GO

CREATE PROCEDURE dbo.stp_RPT_OKC_TRACKINGSTAT
		@DTFrom [datetime],
		@DTTo [datetime],
		@SubSystem varchar(MAX)
AS
BEGIN
	SELECT SUBSYSTEM, TOTAL, TYPE 
	INTO #PTK_PECTRACKING_TEMP
	FROM
	(
		--BAGS SEEN -- TOTAL_BAG
		SELECT MBCR.SUBSYSTEM, SUM(DIFFERENT) AS TOTAL, 'TOTAL_BAG' AS TYPE
		FROM MDS_BAG_COUNT MBC, MDS_BAG_COUNTERS MBCR, LOCATIONS LOC WITH(NOLOCK)
		WHERE MBC.COUNTER_ID=MBCR.COUNTER_ID
			AND MBCR.LOCATION=LOC.LOCATION AND MBCR.SUBSYSTEM=LOC.SUBSYSTEM AND LOC.TRACKED=1 
			--AND EXISTS (SELECT LOCATION FROM LOCATIONS WHERE TRACKED = 1 AND MBCR.LOCATION=LOCATIONS.LOCATION)
			AND MBCR.SUBSYSTEM IN (SELECT * FROM RPT_GETPARAMETERS(@SubSystem))
			AND TIME_STAMP BETWEEN @DTFrom AND @DTTo 
		GROUP BY MBCR.SUBSYSTEM

		UNION	
		SELECT LOC.SUBSYSTEM, COUNT(ITL.GID) AS TOTAL, 'MISS' AS TYPE
		FROM ITEM_LOST ITL, LOCATIONS LOC WITH(NOLOCK)
		WHERE TIME_STAMP BETWEEN @DTFrom AND @DTTo 
			AND ITL.LOCATION=LOC.LOCATION_ID
			AND LOC.SUBSYSTEM IN (SELECT * FROM  RPT_GETPARAMETERS(@SubSystem))
			--AND ITL.LOCATION IN (SELECT LOCATION_ID FROM LOCATIONS WHERE TRACKED = 1)
		GROUP BY LOC.SUBSYSTEM
	) AS TEMP_TBL;

	CREATE TABLE #PTK_PECTRACKING_FINAL
	(
		SUBSYSTEM VARCHAR(20),
		TOTAL_BAG INT,
		MISS INT
	);

	INSERT INTO #PTK_PECTRACKING_FINAL
	SELECT DISTINCT SUBSYSTEM,0 AS TOTAL_BAG, 0 AS MISS
	FROM #PTK_PECTRACKING_TEMP

	UPDATE PPF
	SET PPF.TOTAL_BAG=PPT.TOTAL
	FROM #PTK_PECTRACKING_TEMP PPT,#PTK_PECTRACKING_FINAL PPF
	WHERE PPF.SUBSYSTEM=PPT.SUBSYSTEM 
		AND PPT.TYPE='TOTAL_BAG';
		
	UPDATE PPF
	SET PPF.MISS=PPT.TOTAL
	FROM #PTK_PECTRACKING_TEMP PPT,#PTK_PECTRACKING_FINAL PPF
	WHERE PPF.SUBSYSTEM=PPT.SUBSYSTEM 
		AND PPT.TYPE='MISS';

	SELECT * FROM #PTK_PECTRACKING_FINAL
	ORDER BY SUBSYSTEM;
END