GO
USE [BHSDB];
GO

ALTER PROCEDURE dbo.stp_RPT24_BDDFault
		  @DTFrom datetime, 
		  @DTTo datetime
AS
BEGIN
--What is AA_BDAL
	SELECT	MALM.ALM_ALMEXTFLD2 AS BMA_ID, 
			ALM_STARTTIME, 
			ALM_ENDTIME,
			DATEDIFF(SECOND,ALM_STARTTIME,ALM_ENDTIME) AS FAULT_DUARTION,
			ALM_MSGDESC AS ALM_DESCRIPTION
	FROM	MIS_SS_LINE_DEVICE AS SLD,
			MDS_ALARMS AS MALM WITH(NOLOCK)
	WHERE	MALM.ALM_ALMAREA1=SLD.SUBSYSTEM
			AND MALM.ALM_ALMEXTFLD2 LIKE '%' + DBO.RPT_FORMAT_LOCATION(SLD.BMA_LOCATION) + '%'
			AND ALM_UNCERTAIN = 0
			AND ALM_STARTTIME BETWEEN @DTFrom AND @DTTo 
			AND MALM.ALM_MSGTYPE='ALARM'
	ORDER BY ALM_STARTTIME

	--SELECT     ALM_ALMAREA1, ALM_STARTTIME, ALM_ENDTIME, ALM_MSGDESC
	--FROM         MDS_ALARMS
	--WHERE    (ALM_UNCERTAIN = 0) AND  (ALM_STARTTIME BETWEEN @DTFrom AND @DTTo) AND (ALM_ALMAREA2 = 'AA_BDAL')
	--ORDER BY ALM_STARTTIME

END

--DECLARE @DTFrom datetime='2014-1-7';
--DECLARE @DTTo datetime='2014-1-10';
--EXEC stp_RPT24_BDDFault @DTFrom,@DTTo