--31 Daily CBIS Summary Report

--Total Throughput
SELECT	SUM(MBC.DIFFERENT) AS TotalThroughput
FROM	MIS_SubsystemCatalog SC, MDS_COUNT MBC, MDS_COUNTERS MBCR WITH(NOLOCK)
WHERE	SC.SUBSYSTEM_TYPE='Input Conveyors'
	AND SC.SUBSYSTEM=MBCR.SUBSYSTEM
	AND SC.DETECT_LOCATION=MBCR.LOCATION
	AND MBCR.TYPE='CV'
	AND MBCR.COUNTER_ID=MBC.COUNTER_ID
	AND MBC.TIME_STAMP BETWEEN @DTFrom AND @DTTo 


--BAG VOLUME
stp_RPT_CLT_Simple_BagVolume

--CBIS/BHS Faults/Events
stp_RPT_CLT_Simple_STAT_FAULTEVENT

--Bag Time in CBIS (Minutes)
stp_RPT_CLT_Simple_TimeInSystem