USE [BHSDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER FUNCTION [dbo].[RPT_FORMAT_LOCATION]
(
	@LOCATION VARCHAR(50)
)
RETURNS VARCHAR(50)
AS
BEGIN
	--For example: Convert 'SS1-1' to 'SS1-01'
	--For example: Convert 'SS1-1-M1' to 'SS1-01-M1'
	--For example: Convert 'SS1-1A' to 'SS1-01A'
	DECLARE @FORMAT_LOC VARCHAR(50);
	DECLARE @NUM_PART VARCHAR(50);
	DECLARE @BEFORE_PART VARCHAR(50)=SUBSTRING(@LOCATION,1,CHARINDEX('-',@LOCATION));
	DECLARE @TEMP VARCHAR(50)=SUBSTRING(@LOCATION,CHARINDEX('-',@LOCATION)+1,LEN(@LOCATION)-CHARINDEX('-',@LOCATION));
	DECLARE @AFTER_PART VARCHAR(50)='';
	
	IF ISNUMERIC(@TEMP)<>1
	BEGIN
		IF CHARINDEX('-',@TEMP)>0
		BEGIN
			SET @NUM_PART=SUBSTRING(@TEMP,1,CHARINDEX('-',@TEMP)-1);
			SET @AFTER_PART=SUBSTRING(@TEMP,CHARINDEX('-',@TEMP),LEN(@TEMP)-CHARINDEX('-',@TEMP)+1);
		END
		ELSE
		BEGIN
			SET @NUM_PART=@TEMP;
		END
		
		IF ISNUMERIC(@NUM_PART)<>1
		BEGIN
			IF ISNUMERIC(SUBSTRING(@NUM_PART,1,1))=1 AND ISNUMERIC(SUBSTRING(@NUM_PART,2,1))<>1
			BEGIN
				SET @AFTER_PART=SUBSTRING(@NUM_PART,2,LEN(@NUM_PART))+@AFTER_PART;
				SET @NUM_PART=SUBSTRING(@NUM_PART,1,1);
			END	
		END
	END
	ELSE
	BEGIN
		SET @NUM_PART=@TEMP;
	END

	IF LEN(@NUM_PART)=1 AND ISNUMERIC(@NUM_PART)=1
		SET @NUM_PART='0' + @NUM_PART



	SET @FORMAT_LOC=@BEFORE_PART + @NUM_PART + @AFTER_PART;
	
	RETURN @FORMAT_LOC
END


--SELECT DBO.RPT_FORMAT_LOCATION('SS1-1'),'SS1-1'
--SELECT DBO.RPT_FORMAT_LOCATION('SS1-1-M1'),'SS1-1-M1'
--SELECT DBO.RPT_FORMAT_LOCATION('SS1-1A'),'SS1-1A'
--SELECT DBO.RPT_FORMAT_LOCATION('SS1-1A-M1'),'SS1-1A-M1'
--SELECT DBO.RPT_FORMAT_LOCATION('SS1-12'),'SS1-12'
--SELECT DBO.RPT_FORMAT_LOCATION('SS1-12-M1'),'SS1-12-M1'
--SELECT DBO.RPT_FORMAT_LOCATION('SS1-12B'),'SS1-12B'
--SELECT DBO.RPT_FORMAT_LOCATION('SS1-12B-M1'),'SS1-12B-M1'
--SELECT DBO.RPT_FORMAT_LOCATION('SS1-01'),'SS1-01'
--SELECT DBO.RPT_FORMAT_LOCATION('SS1A-1D'),'SS1A-1D'

--SELECT DBO.RPT_FORMAT_LOCATION('SS1-AA-M1'),'SS1-AA-M1'
--SELECT DBO.RPT_FORMAT_LOCATION('SS1-AA'),'SS1-AA'
--SELECT DBO.RPT_FORMAT_LOCATION('SS1-A-M1'),'SS1-A-M1'
--SELECT DBO.RPT_FORMAT_LOCATION('SS1-A'),'SS1-A'
--SELECT DBO.RPT_FORMAT_LOCATION('SS1-A1'),'SS1-A1'