GO
USE [BHSDB];
GO

CREATE TYPE ALLOCINFO_TABLETYPE AS TABLE 
( 
	AIRLINE varchar(3),
	FLIGHT_NUMBER varchar(5),
	SDO datetime,
	ALLOCINFO VARCHAR(10)
);

CREATE TYPE ALLOCCOMINFO_TABLETYPE AS TABLE
( 
	AIRLINE varchar(3),
	FLIGHT_NUMBER varchar(5),
	SDO datetime,
	COMBINEINFO VARCHAR(200)
);

GO
USE [BHSDB];
GO

CREATE PROCEDURE dbo.stp_RPT_AllocInfoCombine
		  @ALLOCINFO_TABLE AS ALLOCINFO_TABLETYPE readonly
		  --@COMMBINFO_TABLE AS ALLOCCOMINFO_TABLETYPE OUTPUT readonly 
AS
BEGIN
	PRINT 'HELLO';
	
	CREATE TABLE #AI_COMBINEINFO_TEMP
	( 
		AIRLINE varchar(3),
		FLIGHT_NUMBER varchar(5),
		SDO datetime,
		COMBINEINFO VARCHAR(200)
	);
	
	INSERT INTO #AI_COMBINEINFO_TEMP
	SELECT DISTINCT AIRLINE, FLIGHT_NUMBER, SDO, '' AS COMBINEINFO
	FROM @ALLOCINFO_TABLE;
	
	DECLARE @AIRLINE VARCHAR(3);
	DECLARE @FLIGHTNUM VARCHAR(5);
	DECLARE @SDO DATETIME;
	DECLARE @INFO_TABLE TABLE(ALLOCINFO VARCHAR(MAX)); --table variable for tempary allocation data
	
	DECLARE GROUP_CUROR CURSOR FOR SELECT AIRLINE,FLIGHT_NUMBER,SDO  FROM #AI_COMBINEINFO_TEMP;
	OPEN GROUP_CUROR;
	
	FETCH NEXT FROM GROUP_CUROR INTO @AIRLINE,@FLIGHTNUM,@SDO;
	WHILE @@FETCH_STATUS = 0
	BEGIN
	
		DECLARE @INDIVIDUAL_INFO VARCHAR(10);
		DECLARE @COMMBINE_INFO VARCHAR(MAX)='';
		
		INSERT INTO @INFO_TABLE(ALLOCINFO) 
		SELECT DISTINCT ALI.ALLOCINFO 
		FROM @ALLOCINFO_TABLE ALI 
		WHERE (ALI.AIRLINE=@AIRLINE AND ALI.FLIGHT_NUMBER=@FLIGHTNUM AND ALI.SDO=@SDO) ORDER BY ALI.ALLOCINFO
		
		DECLARE INFO_CURSOR CURSOR FOR SELECT ALLOCINFO FROM @INFO_TABLE;
		OPEN INFO_CURSOR
		
		FETCH NEXT FROM INFO_CURSOR INTO @INDIVIDUAL_INFO;
		WHILE @@FETCH_STATUS = 0
		BEGIN
			IF (@INDIVIDUAL_INFO='' OR @INDIVIDUAL_INFO IS NULL)
			BEGIN
				Set @COMMBINE_INFO = @COMMBINE_INFO
			END
			ELSE
			BEGIN
				Set @COMMBINE_INFO = @COMMBINE_INFO + @INDIVIDUAL_INFO + ',';
				FETCH NEXT FROM INFO_CURSOR INTO @INDIVIDUAL_INFO;
			END
		END
		
		Set @COMMBINE_INFO = SUBSTRING(@COMMBINE_INFO,1,LEN(@COMMBINE_INFO)- 1);  --Remove the last 1 comma
		
		CLOSE INFO_CURSOR;
		DEALLOCATE INFO_CURSOR;
		DELETE @INFO_TABLE; --Empty the table variable
							
		UPDATE #AI_COMBINEINFO_TEMP SET COMBINEINFO=@COMMBINE_INFO 
		WHERE AIRLINE=@AIRLINE AND FLIGHT_NUMBER=@FLIGHTNUM AND SDO=@SDO

		FETCH NEXT FROM GROUP_CUROR INTO @AIRLINE,@FLIGHTNUM,@SDO;
	END
	
	CLOSE GROUP_CUROR;
	DEALLOCATE GROUP_CUROR;
	

	SELECT * FROM #AI_COMBINEINFO_TEMP
END