GO
USE [BHSDB];
GO


CREATE PROCEDURE dbo.stp_RPT_OKC_MESUTILIZATION
		  @DTFROM datetime, 
		  @DTTO datetime
AS
BEGIN
	--Modified by Guo Wenyu on 2014/01/02
	--Redesign the report, and do not follow the specification
	--Just show the exact encoded type for telegram-Manual Encoding Request

	DECLARE @MINRANGE INT=10;

	--Create temp table for final result
	CREATE TABLE #MU_MESUTILIZATION_TEMP
	(
		ME_STATION VARCHAR(10),
		CNT_LICENSE_PLATE INT,
		CNT_FLIGHT_NUMBER INT,
		CNT_DESTINATION INT,
		CNT_PROBLEM_BAG INT,
		CNT_ITEM_REMOVED INT,
		CNT_AIRLINE INT,
	);

	--Create temp table for all the required MES data from ITEM_ENCODING_REQUEST 
	--And mark the encoding type
	CREATE TABLE #MU_MESMARKLIST_TEMP
	(
		GID VARCHAR(10),
		TIME_STAMP DATETIME,
		LOCATION VARCHAR(10),
		ENCODING_TYPE VARCHAR(2),
		MARK_LICENSE_PLATE INT,
		MARK_FLIGHT_NUMBER INT,
		MARK_DESTINATION INT,
		MARK_PROBLEM_BAG INT,
		MARK_ITEM_REMOVED INT,
		MARK_AIRLINE INT,
	);

	--1. Query ITEM_ENCODED detail data into #MES_ITEM_ENCODED_TEMP
	SELECT	--MAX(IEC.TIME_STAMP) AS TIME_STAMP,
			IEC.TIME_STAMP,
			IEC.GID,IEC.LOCATION,IEC.ENCODING_TYPE 
	INTO	#MES_ITEM_ENCODED_TEMP
	FROM	ITEM_ENCODED IEC WITH(NOLOCK)
	WHERE	IEC.TIME_STAMP BETWEEN @DTFROM AND @DTTO
		--AND IEC.TIME_STAMP=(SELECT MAX(TIME_STAMP) FROM ITEM_ENCODED IEC2 WITH(NOLOCK) WHERE IEC.GID=IEC2.GID)
		--AND IER.PLC_IDX<>'1001' -- PLC PROBLEM
	--GROUP BY IEC.GID,IEC.LOCATION,IEC.ENCODING_TYPE;

	--2. Query ITEM_REMOVED detail data into #MES_ITEM_REMOVED_TEMP
	SELECT IRM.GID,IRM.TIME_STAMP,IRM.LOCATION
	INTO #MES_ITEM_REMOVED_TEMP 
	FROM ITEM_REMOVED IRM WITH(NOLOCK)
	WHERE IRM.TIME_STAMP BETWEEN @DTFROM AND @DTTO

	--select * from #MU_ITEM_ENCODING_REQUEST_TEMP;

	--3. Initialize MES encoding mark of #MU_MESMARKLIST_TEMP
	--There is only 1 MES in OKC
	INSERT INTO #MU_MESMARKLIST_TEMP
	SELECT IEC.GID, IEC.TIME_STAMP, LOC.SUBSYSTEM AS LOCATION, IEC.ENCODING_TYPE,
		   0 AS MARK_LICENSE_PLATE, 0 AS MARK_FLIGHT_NUMBER, 0 AS MARK_DESTINATION, 
		   0 AS MARK_PROBLEM_BAG, 0 AS MARK_ITEM_REMOVED, 0 AS MARK_AIRLINE
	FROM #MES_ITEM_ENCODED_TEMP IEC, LOCATIONS LOC
	WHERE IEC.LOCATION=LOC.LOCATION_ID AND LOC.SUBSYSTEM LIKE 'ME%'
	UNION
	SELECT IRM.GID, IRM.TIME_STAMP, LOC.SUBSYSTEM AS LOCATION, '5' AS ENCODING_TYPE,
		   0 AS MARK_LICENSE_PLATE, 0 AS MARK_FLIGHT_NUMBER, 0 AS MARK_DESTINATION, 
		   0 AS MARK_PROBLEM_BAG, 1 AS MARK_ITEM_REMOVED, 0 AS MARK_AIRLINE
	FROM   #MES_ITEM_REMOVED_TEMP IRM, LOCATIONS LOC
	WHERE  IRM.LOCATION=LOC.LOCATION_ID AND LOC.SUBSYSTEM LIKE 'ME%'


	--Commented by Guo Wenyu 2014/01/02
	--3	Query ITEM_REDIRECT with Reason: Unknown License Plate into temp table
	--SELECT IRD.GID INTO #MU_ITEM_REDIRECT_TEMP
	--FROM ITEM_REDIRECT IRD, LOCATIONS LOC
	--WHERE IRD.REASON='12'
	--	AND IRD.TIME_STAMP BETWEEN DATEADD(HOUR,-@HOURRANGE,@DTFROM) AND DATEADD(HOUR,@HOURRANGE,@DTTO)
	--	AND (IRD.DESTINATION_1=LOC.LOCATION_ID OR IRD.DESTINATION_2=LOC.LOCATION_ID)
	--	AND LOC.SUBSYSTEM LIKE 'ME%';
	
	--CREATE INDEX #MU_ITEM_REDIRECT_TEMP_IDXGID ON #MU_ITEM_REDIRECT_TEMP(GID);
	--Commented END

	--3. Update each mark of #MU_MESMARKLIST_TEMP according to ENCODING_TYPE

	--Encoded Type. There are following possible values:
	--※1§ 每 Encoded by License Plate Number.
	--※2§ 每 Encoded by Flight Number.
	--※3§ 每 Encoded by Destination.
	--※4§ 每 Encoded by Problem Bag.
	--※5§ 每 Encoded by Item Removed.
	--※6§ 每 Encoded by Airline.

	UPDATE MMT
	SET 
		MARK_LICENSE_PLATE	= CASE MMT.ENCODING_TYPE WHEN '1' THEN 1 ELSE 0 END, 
		MARK_FLIGHT_NUMBER	= CASE MMT.ENCODING_TYPE WHEN '2' THEN 1 ELSE 0 END, 
		MARK_DESTINATION	= CASE MMT.ENCODING_TYPE WHEN '3' THEN 1 ELSE 0 END, 
		MARK_PROBLEM_BAG	= CASE MMT.ENCODING_TYPE WHEN '4' THEN 1 ELSE 0 END, 
		MARK_ITEM_REMOVED	= CASE MMT.ENCODING_TYPE WHEN '5' THEN 1 ELSE 0 END, 
		MARK_AIRLINE		= CASE MMT.ENCODING_TYPE WHEN '6' THEN 1 ELSE 0 END
	FROM #MU_MESMARKLIST_TEMP MMT

	--UPDATE MMT
	--SET MARK_BSM=MARK_SCANNING-MARK_LATEBSMS
	--FROM #MU_MESMARKLIST_TEMP MMT;

	INSERT INTO #MU_MESUTILIZATION_TEMP
	SELECT MMT.LOCATION AS ME_STATION,
		   SUM(MARK_LICENSE_PLATE) AS CNT_LICENSE_PLATE,
		   SUM(MARK_FLIGHT_NUMBER) AS CNT_FLIGHT_NUMBER,
		   SUM(MARK_DESTINATION) AS CNT_DESTINATION,
		   SUM(MARK_PROBLEM_BAG) AS CNT_PROBLEM_BAG,
		   SUM(MARK_ITEM_REMOVED) AS CNT_ITEM_REMOVED,
		   SUM(MARK_AIRLINE) AS CNT_AIRLINE
	FROM #MU_MESMARKLIST_TEMP MMT
	GROUP BY MMT.LOCATION;

	SELECT * FROM #MU_MESUTILIZATION_TEMP;
END


--declare @DTFROM datetime='2014-01-02';
--declare @DTTO datetime='2014-01-03';
--exec stp_RPT09_MESUTILIZATION_GWYTEST @DTFROM,@DTTO;
