GO
USE [BHSDB];
GO

ALTER PROCEDURE dbo.stp_RPT_OKC_EDSSTATS
		  @DTFROM DATETIME,
		  @DTTO DATETIME
AS
BEGIN
--PROBLEM1: only machine(lvl1) result or levle1&2 result
--1	Machine Clear / Operator Clear	MCOC
--2	Machine Alarm / Operator Clear	MAOC
--3	Machine Clear / Operator Alarm	MCOA
--4	Machine Alarm / Operator Alarm	MAOA
--5	Machine Clear / Operator Timed Out	MCOT
--6	Machine Alarm / Operator Timed Out	MAOT
--7	Error / Unknown	UNK/ERR

	DECLARE @DATERANGE INT=1;

	--1. Insert item_screened data into a temp table
	SELECT LOCATION,GID,SCREEN_LEVEL,TIME_STAMP,RESULT_TYPE
	INTO #EDS_ITEM_SCREENED_TEMP
	FROM ITEM_SCREENED WITH(NOLOCK)
	WHERE TIME_STAMP BETWEEN @DTFrom AND @DTTo;

	--2. create a temp table for machine result
	CREATE TABLE #EDS_STATUS_TEMP
	(
		--SUBSYSTEM_TYPE VARCHAR(30),
		SUBSYSTEM VARCHAR(20),
		LOCATION VARCHAR(20),
		BAGS INT,
		BAGS_CLEARED INT,
		BAGS_ALARMED INT,
		CLEARED_RATE FLOAT
	)

	--Insert EDS machines screened result into #EDS_STATUS_TEMP
	--3. total number of bags
	INSERT INTO #EDS_STATUS_TEMP
	SELECT LOC.SUBSYSTEM, LOC.LOCATION, COUNT(ICR.GID) AS BAGS, 0 AS BAGS_CLEARED, 0 AS BAGS_ALARMED, 0 AS CLEARED_RATE
	FROM #EDS_ITEM_SCREENED_TEMP ICR, LOCATIONS LOC
	WHERE ICR.LOCATION=LOC.LOCATION_ID
		--AND ICR.SCREEN_LEVEL='3'
	GROUP BY LOC.SUBSYSTEM, LOC.LOCATION;

	--4. cleared bag
	UPDATE EST
	SET EST.BAGS_CLEARED=CLR.CLEARED_CNT
	FROM
	(
		SELECT LOC.LOCATION,COUNT(ICR.GID) AS CLEARED_CNT
		FROM #EDS_ITEM_SCREENED_TEMP ICR, LOCATIONS LOC
		WHERE LOC.LOCATION_ID=ICR.LOCATION
			--AND ICR.SCREEN_LEVEL='3'
			AND (ICR.RESULT_TYPE='1' OR ICR.RESULT_TYPE='2')--CLEARED
		GROUP BY LOC.LOCATION
	) AS CLR, #EDS_STATUS_TEMP EST
	WHERE EST.LOCATION=CLR.LOCATION;

	--5. alarmed bag
	UPDATE EST
	SET EST.BAGS_ALARMED=ALM.ALARMED_CNT
	FROM
	(
		SELECT LOC.LOCATION,COUNT(ICR.GID) AS ALARMED_CNT
		FROM #EDS_ITEM_SCREENED_TEMP ICR, LOCATIONS LOC
		WHERE LOC.LOCATION_ID=ICR.LOCATION
			--AND ICR.SCREEN_LEVEL='3'
			AND (ICR.RESULT_TYPE<>'1' AND ICR.RESULT_TYPE<>'2')--ALARMED
		GROUP BY LOC.LOCATION
	) AS ALM, #EDS_STATUS_TEMP EST
	WHERE EST.LOCATION=ALM.LOCATION;


	--6. cleared rate
	UPDATE EST
	SET EST.CLEARED_RATE=CAST(BAGS_CLEARED AS FLOAT)/CAST(BAGS AS FLOAT)*100
	FROM #EDS_STATUS_TEMP EST;

	--7. count the bags by different matrix (east and west)
	--And finally select all the result.
	SELECT SUBSYSTEM, BAGS, BAGS_CLEARED,BAGS_ALARMED, CLEARED_RATE
	FROM #EDS_STATUS_TEMP

	

END

--DECLARE @DTFrom [datetime]='2014-03-20';
--DECLARE @DTTo [datetime]='2014-03-22';
--EXEC stp_RPT_OKC_EDSSTATS @DTFrom,@DTTo;

--SELECT * FROM ITEM_SCREEN_RESULT_TYPES;
