USE [BHSDB]
GO
/****** Object:  UserDefinedFunction [dbo].[SAC_OFFSETOPERATOR]    Script Date: 2014/3/24 14:34:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[RPT_CONVERT_MINUTE](@TIME VARCHAR(5)) --@TIME='2345'|| '-0020' || '0020'
RETURNS INT
AS
BEGIN
	
	DECLARE @HOUR INT;
	DECLARE @MIN INT;
	DECLARE @TOTAL_MIN INT;

	IF SUBSTRING(@TIME,1,1)='-' AND LEN(@TIME)=5
	BEGIN
		SET @HOUR = CAST(SUBSTRING(@TIME,2,2) AS INT);
		SET @MIN = CAST(SUBSTRING(@TIME,4,2) AS INT);
		SET @TOTAL_MIN = 0 - @HOUR * 60 - @MIN;
	END
	ELSE IF LEN(@TIME)=4 AND SUBSTRING(@TIME,1,1)<>'-'
	BEGIN
		SET @HOUR = CAST(SUBSTRING(@TIME,1,2) AS INT);
		SET @MIN = CAST(SUBSTRING(@TIME,3,2) AS INT);
		SET @TOTAL_MIN = @HOUR * 60 + @MIN;
	END

	RETURN @TOTAL_MIN;
END

--SELECT DBO.RPT_CONVERT_MINUTE('0945');
--SELECT DBO.RPT_CONVERT_MINUTE('0230');
--SELECT DBO.RPT_CONVERT_MINUTE('-0230');
--SELECT DBO.RPT_CONVERT_MINUTE('-0030');
--SELECT DBO.RPT_CONVERT_MINUTE('0030');