USE [BHSDB]
GO
/****** Object:  UserDefinedFunction [dbo].[SAC_OFFSETOPERATOR]    Script Date: 2014/3/24 14:34:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[RPT_TIME_CAL](@SDO DATETIME, @STO VARCHAR(4), @OFFSET VARCHAR(5)) --@TIME='2345'|| '-0020' || '0020'
RETURNS DATETIME
AS
BEGIN
	
	DECLARE @STDMIN INT = DBO.RPT_CONVERT_MINUTE(@STO);
	DECLARE @OFSMIN INT = DBO.RPT_CONVERT_MINUTE(@OFFSET);
	DECLARE @STD DATETIME = DATEADD(MINUTE,@STDMIN,@SDO);

	RETURN DATEADD(MINUTE,@OFSMIN,@STD);
END

--SELECT [dbo].[RPT_TIME_CAL]('2014-03-23 00:00:00.000','2100','0302');